export const ADD_INSTRUCTOR='ADD_INSTRUCTOR';
export const CHECK_INSTRUCTOR='CHECK_INSTRUCTOR';
export const FIND_INSTRUCTOR='FIND_INSTRUCTOR';
export const FAIL_INSTRUCTOR='FAIL_INSTRUCTOR';
export const FIND_ADD_INSTRUCTOR='FIND_ADD_INSTRUCTOR';
export const FAIL_ADD_INSTRUCTOR='FAIL_ADD_INSTRUCTOR';

